### PR TITLE
Fix validate float

### LINKED ISSUE #60: float and float* fields accept string values
This code demonstrates that it's possible to pass string values to float and float* fields and it doesn't cause validation to fail:

```lua
#!/usr/bin/env tarantool

local avro = require('avro_schema')
local json = require('json')

local model = [[
[
    {
    "name": "Foo",
    "type": "record",
    "fields": [
        {"name": "foo", "type": "float*"}
    ]
    }
]
]]


local dict = json.decode(model)

local ok, schema = avro.create(dict)

if not ok then
    error(schema)
end


local obj = {foo="0"}

local ok, normalized = avro.validate(schema, {Foo=obj})

if not ok then
    error(normalized)
end

```

### PR DESCRIPTION
**Pull request by Khatskevich**
Before this commit it was allowed to pass `"0"` to float or double
field, because it the validator were using `tonumber` function.

The behavior is changed due to the following reasons:
- This behavior is not added intentionally (It is from initial commit).
- A compiled schema cannot flatten a string even if it can be cast to
  float.
- Int or long types do not allow strings at all.

Closes #60

### CODE REVIEW

File: avro_schema/frontend.lua [hunk 1]
```diff
@@ -665,7 +665,15 @@ copy_data = function(schema, data, visited)
         end
         return data
     elseif schematype == 'double' or schematype == 'float' then
-        return 0 + tonumber(data)
+        local xtype = type(data)
+        if xtype == "number" then
+            return data
+        else
+            if xtype == "cdata" then
```
Comment (Totktonada) [inline avro_schema/frontend.lua]: Do you want to check for our implementation of number64? Is it worth to check stricter?

```
type(data) == 'cdata' and tostring(ffi.typeof(data)) == 'ctype<uint64_t>'
```

**Comment by Totktonada** [comment]
Added minor comment. LGTM, ok to push.

File: avro_schema/frontend.lua (hunk 1 above)
Comment (Khatskevich) [reply avro_schema/frontend.lua]: 1. There is a bunch of possible types, e.g. `1LL` is `ctype<int64_t>`, char, short, long, float...
2. I think that rely on `tonumber` function is ok, which mean that we should only check that `tonumber` result is not `nil`

Comment (Totktonada) [reply avro_schema/frontend.lua]: Good point.

**Comment by Totktonada** [comment]
LGTM.
