### PR TITLE
Fix case when "long" type validation allows field to have a "string" type

### LINKED ISSUE #133: validation for "long" allows "string"
```
tarantool> avro_schema.validate(select(2, avro_schema.create('long')), '42')
---
- true
- '42'
...

tarantool> avro_schema.validate(select(2, avro_schema.create('long')), 42)
---
- true
- 42
...
```

Broken here - https://github.com/tarantool/avro-schema/commit/23be8480e153521772adf6317f04c7d03c65a67c

### PR DESCRIPTION
**Pull request by olegrok**
Since 23be848 (Validate/long: final rewrite) "long" type
validation started to handle string representation of numbers.
This happens because "tonumber" function implicitly casts some
strings to numbers. That allows to pass strings (e.g. "123") instead
of "long".

This patch fixes such behaviour and introduces corresponding
test. Currently we will try to cast to number only fields that
have "number" or "cdata" type.

Closes #133

### CODE REVIEW

File: avro_schema/frontend.lua [hunk 1]
```diff
@@ -769,7 +769,10 @@ copy_data = function(stack, schema, data, visited)
         stack.remove_last()
         return data
     elseif schematype == 'long' then
-        local n = tonumber(data)
+        local n
+        if type(data) == 'number' or type(data) == 'cdata' then
+            n = tonumber(data)
+        end
```
Comment (olegrok) [inline avro_schema/frontend.lua:775]: Alternative way that also could be used.
Do something like

```lua
local _
_ = data > 0 -- it throws for non-numeric types (e.g. for strings)
```

**Comment by Totktonada** [comment]
23be8480e153521772adf6317f04c7d03c65a67c is weird: it does not explain why to use such hacky way to validate a value. Better for JIT? Observed better performance?

The code version before 23be8480e153521772adf6317f04c7d03c65a67c is easier to understand and now we anyway check the type explicitly. Maybe it would be logical to just revert the commit. However I don't mind your minimal change.

**Comment by Totktonada** [comment]
At least is solved the observed problem and does not lead to any visible functional degradation.

**Review by Totktonada — APPROVED** [review]
LGTM.
