### PR TITLE
Module reload

### LINKED ISSUE #34: Can't reload code of avro-schema
When I set `package.loaded['avro-schema'] = nil` and attempt to `require()` it again, I get:

```lua
tarantool> ---
- error: '...antool/ib-core/.rocks/share/tarantool/avro_schema/il.lua:12: attempt
    to redefine ''schema_il_Opcode'''
...
```

UPD: ability to do hot code reload is very important for my development workflow

### PR DESCRIPTION
**Pull request by olegrok**
Commit fixes error that is thrown on package reload

Closes #34

### CODE REVIEW

File: avro_schema/il.lua [hunk 1]
```diff
@@ -9,7 +9,7 @@ local insert, remove = table.insert, table.remove
 local concat         = table.concat
 local max            = math.max
 
-ffi.cdef([[
+pcall(ffi.cdef, [[
```
Comment (Totktonada) [inline avro_schema/il.lua]: I would do it strictier: check for ffi.C.schema_il_Opcode and if it present, then assert that ffi.C.schema_il_V is here too. If it is not present assert that ffi.C.schema_il_V is not present too and do ffi.cdef w/o pcall.

Comment (Totktonada) [reply avro_schema/il.lua]: It seems pcall(ffi.new, 'struct schema_il_Opcode') does the trick.

Comment (olegrok) [reply avro_schema/il.lua]: Fixed

And test case was added
