### PR TITLE
validate: treat lack of value for union field as null

### LINKED ISSUE #64: Nullability is broken inside unions
Related to #35 
```
local schema = json.decode([[{
    "name": "user_collection",
        "type": "record",
        "fields": [
            { "name": "user_id", "type": "string" },
            { "name": "stuff", "type": [ "null", "string","int" ] }
        ]
    }
}]])

obj = { user_id = 'user_id_1' }
local _, schema = avro_schema.create(schema)
local ok, err = avro_schema.validate(schema, obj)
print(ok)
if not ok then 
    print(err)
end
...
ok = false
err = 'Field stuff missing'
```

### PR DESCRIPTION
**Pull request by Totktonada**
Fixes #64.

### CODE REVIEW

File: test/ddt_suite/validate.lua [hunk 1]
```diff
@@ -448,6 +448,27 @@ for schema_no = 1,#records do
 
 end
 
+_G['schema_no'] = nil
+
+-- record union
+
+local foo = [[{
```
Comment (Khatskevich) [inline test/ddt_suite/validate.lua]: Please, inline the schema or give it more descriptive name

File: test/ddt_suite/record_union.lua [hunk 2]
```diff
@@ -15,6 +15,17 @@ t {
...
+--[[
+-- gh-64: treat lack of value (B) as null;
+-- validate was fixed, but flatten didn't
+t {
+    schema = foo,
+    func = 'flatten',
+    input = '{"A":"Hello, world!","C":42}',
+    output = '["Hello, world!", 0, null, 42]'
+}
+]]--
```
Comment (Khatskevich) [inline test/ddt_suite/record_union.lua]: I prefer not add this comment, because 
1. the person who will implement this feature can forget about this comment and add his own test
2. It is very easy to write the test

File: test/ddt_suite/validate.lua (hunk 1 above)
Comment (Totktonada) [reply test/ddt_suite/validate.lua]: `record_union` (to match other names within the file) is okay?

File: test/ddt_suite/record_union.lua (hunk 2 above)
Comment (Totktonada) [reply test/ddt_suite/record_union.lua]: I would prefer to leave it here as some kind of problem statement for a developer.

Alternatively I can close gh-64 here and file separate issue re flatten.

File: test/ddt_suite/validate.lua (hunk 1 above)
Comment (Khatskevich) [reply test/ddt_suite/validate.lua]: I prefer something like 
`schema_blank_nullable_field`

File: test/ddt_suite/record_union.lua (hunk 2 above)
Comment (Khatskevich) [reply test/ddt_suite/record_union.lua]: I do not agree, but I do not insist. It is ok.

File: test/ddt_suite/validate.lua (hunk 1 above)
Comment (Totktonada) [reply test/ddt_suite/validate.lua]: 'blank_nullable_field' is not a property of the schema. Bored with this, will inline.

File: test/ddt_suite/record_union.lua (hunk 2 above)
Comment (Totktonada) [reply test/ddt_suite/record_union.lua]: Do you not agree with which of the two statements above?

Comment (Khatskevich) [reply test/ddt_suite/record_union.lua]: I do not agree that this comment is suitable for the patch.
However, in case you insist let it be here instead of closing #64

Comment (Totktonada) [reply test/ddt_suite/record_union.lua]: Already marked #64 for closing and opened #67 as follow up.
